name: Test unpinned dependencies

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Create/activate venv
      run: |
        uv venv --python ${{ matrix.python-version }}
        source .venv/bin/activate

    - name: Install cudaq
      # Due to a known issue with uv failing to install cudaq on first try,
      # we manually install it twice in a row
      # See https://github.com/astral-sh/uv/issues/12759
      run: |
        uv pip install cudaq
        uv pip install cudaq

    - name: Install package with dev deps
      run: uv pip install -e .[dev]

    - name: Pytest
      run: uv run python -m pytest
      env:
        GUROBI_WLSACCESSID: ${{ vars.GUROBI_WLSACCESSID }}
        GUROBI_LICENSEID: ${{ vars.GUROBI_LICENSEID }}
        GUROBI_WLSSECRET: ${{ secrets.GUROBI_WLSSECRET }}