name: Test pinned dependencies

on:
  push:
    branches: [ main, develop, vb/gurobi_lic ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Create/activate venv
      run: |
        uv venv --python ${{ matrix.python-version }}
        source .venv/bin/activate

    - name: Install requirements
      run: uv pip install -r requirements.txt

    - name: Install package with no deps
      run: uv pip install -e . --no-deps

    - name: Pre-commit checks
      run: |
          uvx pre-commit run --all-files

    - name: Pytest with coverage
      run: |
        uv run python -m pytest
      env:
        GUROBI_WLSACCESSID: ${{ vars.GUROBI_WLSACCESSID }}
        GUROBI_LICENSEID: ${{ vars.GUROBI_LICENSEID }}
        GUROBI_WLSSECRET: ${{ secrets.GUROBI_WLSSECRET }}